version: "2"

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kamilov/go-template)
    goimports:
      local-prefixes: github.com/kamilov/go-template
    golines:
      max-len: 120
      tab-len: 2
  enable:
    - gci
    - goimports
    - golines

linters:
  default: none
  settings:
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    cyclop:
      max-complexity: 30
      package-average: 10.0
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
    gochecksumtype:
      default-signifies-exhaustive: true
    inamedparam:
      skip-single-param: true
    loggercheck:
      slog: true
    sloglint:
      no-global: all
      msg-style: lowercased
      context: scope
    usetesting:
      os-temp-dir: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - cyclop
          - err113
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - lll
          - wrapcheck
